spring:
  docker:
    compose:
      file: "../docker-compose.yml"
  jpa:
    generate-ddl: true
    open-in-view: false
  mail:
    host: localhost
    port: 1025
    username: ntl7d
    password: 123
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate_account
  file:
    upload:
      photo-output-path: ./uploads
